"""Declared wire-frame models for the terminal WebSocket (#692 · T687-3).

The single *structural* source of truth for the ``/ws/terminal`` frames. The
consumer (:mod:`terminals.consumers`) validates an incoming ``init`` frame's
shape from these models, then layers the imperative semantic rules (geometry
clamping, mutually-exclusive spawn modes, doc-path safety, task-scope
requirement) on top — those rules are deliberately *not* encoded here.

The same models export a committed JSON-Schema artifact
(``studio/src/shared/api/transport/wire-frames.schema.json``, via
``manage.py export_wire_frames``) that the Studio contract test diffs its frame
*builders* against. A dropped required field — the CODIN-685 missing-``mode``
bug class — therefore fails CI on both the Python and the TypeScript side.

Scope here is structure only: field presence, types, the ``agent`` enum, and
the spawn/attach ``mode`` discriminant.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel


class InitSpawnFrame(BaseModel):
    """Client → server: spawn a fresh agent terminal (``mode:"spawn"``)."""

    type: Literal["init"]
    mode: Literal["spawn"]
    agent: Literal["claude", "agy", "codex", "gemini"]
    project_id: str
    module_id: str
    task_id: Optional[str]
    initial_prompt: Optional[str]
    cols: int
    rows: int
    is_planning: bool
    is_instant: bool
    instant_prompt: Optional[str]
    is_doc_chat: bool
    doc_rel_path: Optional[str]
    doc_id: Optional[str]


class InitAttachFrame(BaseModel):
    """Client → server: attach to a durable terminal (``mode:"attach"``)."""

    type: Literal["init"]
    mode: Literal["attach"]
    agent_run_id: str
    cols: int
    rows: int


class ReadyFrame(BaseModel):
    """Server → client: the session is live and streaming."""

    type: Literal["ready"]
    session_id: str
    agent_run_id: Optional[str] = None


class ResizeFrame(BaseModel):
    """Client → server: terminal geometry changed."""

    type: Literal["resize"]
    cols: int
    rows: int


class ScrollFrame(BaseModel):
    """Client → server: wheel/trackpad scroll bridged to tmux copy-mode (#578)."""

    type: Literal["scroll"]
    dir: Literal["up", "down"]
    lines: int


class ErrorFrame(BaseModel):
    """Server → client: a terminal error before/at close."""

    type: Literal["error"]
    message: str


# Order is cosmetic only; the exported schema is a plain ``oneOf`` over them.
WIRE_FRAME_MODELS = [
    InitSpawnFrame,
    InitAttachFrame,
    ReadyFrame,
    ResizeFrame,
    ScrollFrame,
    ErrorFrame,
]


def wire_frames_schema() -> dict:
    """Build the committed JSON-Schema artifact for every wire frame.

    A plain ``oneOf`` (not an OpenAPI ``discriminator``) so a draft-07 validator
    such as ``ajv`` — with no discriminator support — still resolves a built
    frame to exactly one branch: the ``type``/``mode`` ``const`` constraints make
    the branches mutually exclusive, and a frame missing its discriminant or any
    required field matches *zero* branches and is rejected.
    """

    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Terminal WebSocket wire frames",
        "description": (
            "Generated by `manage.py export_wire_frames` from "
            "terminals/frames.py. Do not edit by hand."
        ),
        "oneOf": [model.model_json_schema() for model in WIRE_FRAME_MODELS],
    }
