export const OWNER_ID = "task-worktree-owner";
export const TASK_ID = "child-with-committed-work";

export const activeCleanWorktree = {
  __typename: "WorktreeStatusView",
  kind: "worktree",
  task_id: TASK_ID,
  top_level_task_id: OWNER_ID,
  is_shared: true,
  branch: "wt/CODING-1321-task-worktree-changes",
  base_branch: "main",
  path: "/worktrees/CODING-1321-task-worktree-changes",
  state: "active",
  clean: true,
  dirty: false,
  ahead: 1,
  behind: 0,
  conflict: false,
  checkout_present: true,
  ephemeral: false,
  reason: null,
};

export const cumulativeChanges = {
  __typename: "WorktreeChangesView",
  task_id: TASK_ID,
  top_level_task_id: OWNER_ID,
  is_shared: true,
  base_commit: "0123456789abcdef0123456789abcdef01234567",
  committed_count: 1,
  pull_request_url: null,
  pull_request_creation_eligible: true,
  work_item_done: false,
  closure_failure: null,
  cleanup: {
    __typename: "WorktreeCleanupStatusView",
    eligible: false,
    blocker: "pull_request_absent",
    reason: "No pull request is mapped to this worktree.",
  },
  pull_request: {
    __typename: "PullRequestStatusView",
    url: null,
    state: "none",
    target_branch: null,
    head_commit: null,
    integrated: false,
    post_merge_work: false,
    replacement_eligible: false,
    follow_up_eligible: false,
    merge_preparation_eligible: false,
    reason: null as string | null,
  },
  clean: true,
  dirty: false,
  unpushed_count: 1,
  truncated: false,
  files: [
    ["src/added.ts", "added", null],
    ["src/untracked.ts", "untracked", null],
    ["src/modified.ts", "modified", null],
    ["src/deleted.ts", "deleted", null],
    ["src/renamed.ts", "renamed", "src/old-name.ts"],
    ["src/copied.ts", "copied", "src/original.ts"],
    ["src/conflicted.ts", "conflicted", null],
  ].map(([path, status, previousPath]) => ({
    __typename: "ChangedFile",
    path,
    status,
    previous_path: previousPath,
    binary: false,
    insertions: 1,
    deletions: 1,
  })),
  insertions: 7,
  deletions: 7,
};
