# Generated by Django 6.0.6 on 2026-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('workspace_slug', models.CharField(null=True)),
                ('project_id', models.CharField()),
                ('module_id', models.CharField()),
                ('task_id', models.CharField(null=True)),
                ('ticket_seq', models.IntegerField(null=True)),
                ('agent', models.CharField()),
                ('status', models.CharField()),
                ('started_at', models.CharField()),
                ('ended_at', models.CharField(null=True)),
                ('exit_code', models.IntegerField(null=True)),
                ('error', models.CharField(null=True)),
                ('cwd', models.CharField(null=True)),
                ('provider_session_id', models.CharField(null=True)),
                ('lifecycle_state', models.CharField(null=True)),
                ('lifecycle_updated_at', models.CharField(null=True)),
                ('design_dir', models.CharField(null=True)),
            ],
            options={
                'db_table': 'agent_runs',
                'indexes': [models.Index(fields=['task_id', '-started_at'], name='idx_agent_runs_task_started_at')],
            },
        ),
        migrations.RunSQL(
            sql="""
                DROP TABLE agent_runs;
                CREATE TABLE agent_runs (
                    id VARCHAR NOT NULL,
                    workspace_slug VARCHAR,
                    project_id VARCHAR NOT NULL,
                    module_id VARCHAR NOT NULL,
                    task_id VARCHAR,
                    ticket_seq INTEGER,
                    agent VARCHAR NOT NULL,
                    status VARCHAR NOT NULL,
                    started_at VARCHAR NOT NULL,
                    ended_at VARCHAR,
                    exit_code INTEGER,
                    error VARCHAR,
                    cwd VARCHAR,
                    provider_session_id VARCHAR,
                    lifecycle_state VARCHAR,
                    lifecycle_updated_at VARCHAR,
                    design_dir VARCHAR,
                    PRIMARY KEY (id)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
