# Generated by Django 5.2.10 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0005_automationattempt_retry"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="scope",
            field=models.CharField(null=True),
        ),
    ]
