# Generated by Django 6.0.6 on 2026-08-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0013_agentrun_launch_configuration_snapshot'),
        ('runs', '0014_agentrun_launch_metadata'),
    ]

    operations = [
    ]
