# Generated by Django 5.2.17 on 2026-08-24 09:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("worktracker", "0051_codex_5_3_model_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_id", models.UUIDField(editable=False, unique=True)),
                (
                    "checkout_kind",
                    models.CharField(
                        choices=[
                            ("base", "Base checkout"),
                            ("worktree", "Task worktree"),
                        ],
                        max_length=16,
                    ),
                ),
                ("checkout_name", models.CharField(max_length=512)),
                ("branch", models.CharField(max_length=512)),
                ("commit_shas", models.JSONField(blank=True)),
                ("commit_outcome", models.JSONField()),
                ("push_outcome", models.JSONField()),
                ("create_pr_outcome", models.JSONField()),
                ("pr_url", models.CharField(blank=True, max_length=2048, null=True)),
                ("pr_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pr_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("action_at", models.DateTimeField()),
                ("pr_refreshed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_ship_records",
                        to="worktracker.issue",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_ship_records",
                        to="worktracker.issue",
                    ),
                ),
            ],
            options={
                "ordering": ("-action_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["module", "-action_at"], name="ship_module_time_idx"
                    ),
                    models.Index(
                        fields=["task", "-action_at"], name="ship_task_time_idx"
                    ),
                    models.Index(
                        condition=models.Q(("pr_url__isnull", False)),
                        fields=["task", "-action_at"],
                        name="ship_task_pr_time_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("checkout_kind", "worktree"),
                            ("task__isnull", True),
                            _connector="OR",
                        ),
                        name="ship_checkout_task_matches_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("pr_state__isnull", True),
                            ("pr_state__in", ("open", "merged", "closed")),
                            _connector="OR",
                        ),
                        name="ship_pr_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("pr_number__isnull", True),
                                ("pr_state__isnull", True),
                                ("pr_url__isnull", True),
                            ),
                            models.Q(
                                ("pr_state__isnull", False),
                                ("pr_url__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ship_pr_facts_complete",
                    ),
                ],
            },
        ),
    ]
