# Generated by Django 6.0.6 on 2026-06-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTerminalSession',
            fields=[
                ('agent_run', models.OneToOneField(db_column='agent_run_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='runs.agentrun')),
                ('tmux_session_name', models.CharField()),
                ('task_id', models.CharField()),
                ('module_id', models.CharField()),
                ('project_id', models.CharField()),
                ('agent', models.CharField()),
                ('created_at', models.CharField()),
                ('terminated_at', models.CharField(null=True)),
                ('scope', models.CharField(db_default='task')),
                ('doc_rel_path', models.CharField(null=True)),
            ],
            options={
                'db_table': 'agent_terminal_sessions',
                'indexes': [models.Index(fields=['task_id', 'terminated_at', '-created_at'], name='idx_agent_terminal_sessions_task_created')],
            },
        ),
        migrations.RunSQL(
            sql="""
                DROP TABLE agent_terminal_sessions;
                CREATE TABLE agent_terminal_sessions (
                    agent_run_id VARCHAR NOT NULL,
                    tmux_session_name VARCHAR NOT NULL,
                    task_id VARCHAR NOT NULL,
                    module_id VARCHAR NOT NULL,
                    project_id VARCHAR NOT NULL,
                    agent VARCHAR NOT NULL,
                    created_at VARCHAR NOT NULL,
                    terminated_at VARCHAR,
                    scope VARCHAR DEFAULT 'task' NOT NULL,
                    doc_rel_path VARCHAR,
                    PRIMARY KEY (agent_run_id),
                    FOREIGN KEY(agent_run_id)
                        REFERENCES agent_runs (id) ON DELETE CASCADE
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
