# Generated by Django 6.0.6 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("terminals", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AgentRunViewerLease",
            fields=[
                (
                    "agent_run",
                    models.OneToOneField(
                        db_column="agent_run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="runs.agentrun",
                    ),
                ),
                ("viewer_id", models.CharField(max_length=64)),
                ("transport", models.CharField(max_length=16)),
                ("acquired_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={"db_table": "agent_run_viewer_leases"},
        ),
    ]
