# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminals", "0002_agent_run_viewer_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentterminalsession",
            name="runtime_cleanup_pending",
            field=models.BooleanField(default=False),
        ),
    ]
