# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminals", "0003_agentterminalsession_runtime_cleanup_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentterminalsession",
            name="runtime_namespace",
            field=models.CharField(
                db_index=True,
                max_length=64,
                null=True,
            ),
        ),
    ]
