# Generated by Django 6.0.6 on 2026-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_agentterminalsession_runtime_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLaunchRequest',
            fields=[
                ('effect_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('agent_run_id', models.CharField(max_length=255, unique=True)),
                ('issue_id', models.CharField(max_length=64)),
                ('project_id', models.CharField(max_length=64)),
                ('module_id', models.CharField(max_length=64)),
                ('task_id', models.CharField(max_length=64)),
                ('agent', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=32)),
                ('doc_rel_path', models.CharField(null=True)),
                ('command', models.TextField()),
                ('working_directory', models.CharField()),
                ('environment', models.JSONField(default=dict)),
                ('columns', models.PositiveIntegerField(default=80)),
                ('rows', models.PositiveIntegerField(default=24)),
                ('created_at', models.CharField()),
            ],
            options={
                'db_table': 'terminal_launch_requests',
            },
        ),
    ]
