# Generated by Django 6.0.6 on 2026-08-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0005_terminallaunchrequest'),
        ('terminals', '0007_restore_agent_run_fk_cascade'),
    ]

    operations = [
    ]
