# Generated by Django 6.0.6 on 2026-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0008_merge_20260819_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminallaunchrequest',
            name='agent',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
