# Generated by Django 6.0.6 on 2026-07-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worktracker', '0009_issue_lifecycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='engine_run', serialize=False, to='worktracker.issue')),
                ('agent', models.CharField(max_length=255)),
                ('phase', models.CharField(default='implement', max_length=50)),
                ('status', models.CharField(default='idle', max_length=50)),
                ('agent_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(db_column='module_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_engine_runs', to='worktracker.issue')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='engine_runs', to='worktracker.project')),
            ],
            options={
                'db_table': 'engine_runs',
            },
        ),
    ]
