# Generated by Django 6.0.6 on 2026-07-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('worktracker', '0009_issue_lifecycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRun',
            fields=[
                ('root', models.OneToOneField(db_column='root_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='graph_run', serialize=False, to='worktracker.issue')),
                ('agent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(db_column='module_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_graph_runs', to='worktracker.issue')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='graph_runs', to='worktracker.project')),
            ],
            options={
                'db_table': 'graph_runs',
            },
        ),
    ]
