# Generated by Django 6.0.6 on 2026-08-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_nullable_agent_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginerun',
            name='phase',
        ),
    ]
