# Generated by Django 6.0.6 on 2026-08-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_remove_enginerun_phase'),
        ('worktracker', '0036_issue_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchedTask',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='launched_task', serialize=False, to='worktracker.issue')),
                ('agent_run_id', models.CharField(max_length=255)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('root', models.ForeignKey(db_column='root_id', on_delete=django.db.models.deletion.CASCADE, related_name='launched_subtree_tasks', to='worktracker.issue')),
            ],
            options={
                'db_table': 'launched_tasks',
            },
        ),
        migrations.DeleteModel(
            name='EngineRun',
        ),
    ]
