# Generated by Django 6.0.6 on 2026-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('pk', models.CompositePrimaryKey('scope', 'key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField()),
                ('key', models.CharField()),
                ('value', models.CharField()),
                ('updated_at', models.CharField()),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.RunSQL(
            sql="""
                DROP TABLE app_settings;
                CREATE TABLE app_settings (
                    scope VARCHAR NOT NULL,
                    "key" VARCHAR NOT NULL,
                    value VARCHAR NOT NULL,
                    updated_at VARCHAR NOT NULL,
                    PRIMARY KEY (scope, "key")
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
