-- Generated by scripts/installation_corpus.py. Do not edit.
-- generation: django-current
-- product-tables: 24
-- product-schema-fingerprint: ceeb53949045404c7f52774835c20cdcb60fedab890d0fccbc35111ec26a9eea
--
-- The schema an empty installation is provisioned into, read back out
-- of a database Django's own migration executor built. Provisioning
-- replays these statements and then verifies that the product schema
-- it produced reproduces the fingerprint recorded above, so a drifted
-- artifact refuses a first launch instead of shaping it wrongly.

CREATE TABLE "agent_run_viewer_leases" (
    "agent_run_id" varchar NOT NULL PRIMARY KEY
        REFERENCES "agent_runs" ("id") ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    "viewer_id" varchar(64) NOT NULL,
    "transport" varchar(16) NOT NULL,
    "acquired_at" datetime NOT NULL,
    "expires_at" datetime NOT NULL
);
CREATE TABLE "agent_runs" ("id" varchar NOT NULL PRIMARY KEY, "ticket_seq" integer NULL, "status" varchar NOT NULL, "started_at" varchar NOT NULL, "ended_at" varchar NULL, "exit_code" integer NULL, "error" varchar NULL, "cwd" varchar NULL, "provider_session_id" varchar NULL, "lifecycle_state" varchar NULL, "lifecycle_updated_at" varchar NULL, "design_dir" varchar NULL, "resumed_from" varchar NULL, "scope" varchar NOT NULL, "issue_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "agent" varchar NULL, "launch_state" varchar NULL, "launch_model" varchar NULL, "model" varchar NULL, "reasoning" varchar NULL);
CREATE TABLE "agent_terminal_sessions" (
    "agent_run_id" varchar NOT NULL PRIMARY KEY
        REFERENCES "agent_runs" ("id") ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    "tmux_session_name" varchar NOT NULL,
    "task_id" varchar NOT NULL,
    "module_id" varchar NOT NULL,
    "project_id" varchar NOT NULL,
    "created_at" varchar NOT NULL,
    "terminated_at" varchar NULL,
    "scope" varchar DEFAULT 'task' NOT NULL,
    "doc_rel_path" varchar NULL,
    "runtime_cleanup_pending" bool NOT NULL,
    "runtime_namespace" varchar(64) NULL,
    "output_identity" varchar(64) NULL,
    "output_sequence" bigint NOT NULL,
    "last_output_at" varchar NULL,
    "agent" varchar NULL
);
CREATE TABLE app_settings (
                    scope VARCHAR NOT NULL,
                    "key" VARCHAR NOT NULL,
                    value VARCHAR NOT NULL,
                    updated_at VARCHAR NOT NULL,
                    PRIMARY KEY (scope, "key")
                );
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "automation_attempts" ("id" char(32) NOT NULL PRIMARY KEY, "transition_id" char(32) NOT NULL, "from_state_id" char(32) NOT NULL, "to_state_id" char(32) NOT NULL, "workflow_revision" integer unsigned NOT NULL CHECK ("workflow_revision" >= 0), "status" varchar(16) NOT NULL, "agent" varchar(64) NULL, "agent_run_id" varchar(255) NULL, "error" text NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "issue_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "error_details" text NULL CHECK ((JSON_VALID("error_details") OR "error_details" IS NULL)), "retryable" bool NOT NULL, "retry_of_id" char(32) NULL UNIQUE REFERENCES "automation_attempts" ("id") DEFERRABLE INITIALLY DEFERRED, "root_attempt_id" char(32) NULL REFERENCES "automation_attempts" ("id") DEFERRABLE INITIALLY DEFERRED, "dismissed_at" datetime NULL);
CREATE TABLE design_documents (
                    id VARCHAR NOT NULL,
                    module_id VARCHAR NOT NULL,
                    task_id VARCHAR NOT NULL,
                    scope VARCHAR NOT NULL,
                    root_dir VARCHAR NOT NULL,
                    rel_path VARCHAR NOT NULL,
                    discovered_by_run_id VARCHAR,
                    created_at VARCHAR NOT NULL,
                    updated_at VARCHAR NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT uq_design_doc_path UNIQUE (root_dir, rel_path)
                );
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "graph_runs" ("root_id" char(32) NOT NULL PRIMARY KEY REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "agent" varchar(255) NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "module_id" char(32) NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "project_id" char(32) NOT NULL REFERENCES "worktracker_project" ("id") DEFERRABLE INITIALLY DEFERRED, "execution_mode" varchar(16) NOT NULL, "launch_configuration" text NULL CHECK ((JSON_VALID("launch_configuration") OR "launch_configuration" IS NULL)));
CREATE TABLE "launch_policy_effects" ("decision_id" varchar(32) NOT NULL PRIMARY KEY, "caller_scope" varchar(32) NOT NULL, "idempotency_key" varchar(255) NOT NULL, "result" text NULL CHECK ((JSON_VALID("result") OR "result" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, CONSTRAINT "uniq_launch_policy_effect_identity" UNIQUE ("caller_scope", "idempotency_key"));
CREATE TABLE "launched_tasks" ("task_id" char(32) NOT NULL PRIMARY KEY REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "agent_run_id" varchar(255) NOT NULL, "launched_at" datetime NOT NULL, "root_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "terminal_launch_requests" ("effect_id" varchar(64) NOT NULL PRIMARY KEY, "agent_run_id" varchar(255) NOT NULL UNIQUE, "issue_id" varchar(64) NOT NULL, "project_id" varchar(64) NOT NULL, "module_id" varchar(64) NOT NULL, "task_id" varchar(64) NOT NULL, "scope" varchar(32) NOT NULL, "doc_rel_path" varchar NULL, "command" text NOT NULL, "working_directory" varchar NOT NULL, "environment" text NOT NULL CHECK ((JSON_VALID("environment") OR "environment" IS NULL)), "columns" integer unsigned NOT NULL CHECK ("columns" >= 0), "rows" integer unsigned NOT NULL CHECK ("rows" >= 0), "created_at" varchar NOT NULL, "agent" varchar(64) NULL);
CREATE TABLE "worktracker_agentmodel" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "provider_id" char(32) NOT NULL REFERENCES "worktracker_provider" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_agent_model_provider_name" UNIQUE ("provider_id", "name"));
CREATE TABLE "worktracker_agentmodelreasoninglevel" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "agent_model_id" char(32) NOT NULL REFERENCES "worktracker_agentmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "reasoning_level_id" char(32) NOT NULL REFERENCES "worktracker_reasoninglevel" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_agent_model_reasoning_level" UNIQUE ("agent_model_id", "reasoning_level_id"));
CREATE TABLE "worktracker_attachment" ("id" char(32) NOT NULL PRIMARY KEY, "file" varchar(100) NOT NULL, "filename" varchar(512) NOT NULL, "mime_type" varchar(255) NOT NULL, "size" integer unsigned NULL CHECK ("size" >= 0), "created_at" datetime NOT NULL, "issue_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "worktracker_issue" ("id" char(32) NOT NULL PRIMARY KEY, "type" varchar(10) NOT NULL, "name" varchar(512) NOT NULL, "sequence_id" integer unsigned NOT NULL CHECK ("sequence_id" >= 0), "description" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "project_id" char(32) NOT NULL REFERENCES "worktracker_project" ("id") DEFERRABLE INITIALLY DEFERRED, "state_id" char(32) NULL REFERENCES "worktracker_state" ("id") DEFERRABLE INITIALLY DEFERRED, "is_archived" bool NOT NULL, "rank" varchar(64) NOT NULL, "state_revision" bigint unsigned NOT NULL CHECK ("state_revision" >= 0), "issue_type_id" char(32) NOT NULL REFERENCES "worktracker_issuetype" ("id") DEFERRABLE INITIALLY DEFERRED, "parent_id" char(32) NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "module_id" char(32) NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "worktracker_issue_blocked_by" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_issue_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED, "to_issue_id" char(32) NOT NULL REFERENCES "worktracker_issue" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "worktracker_issuetype" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "level" varchar(10) NOT NULL, "color" varchar(32) NOT NULL, "sort_order" integer unsigned NOT NULL CHECK ("sort_order" >= 0), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "project_id" char(32) NOT NULL REFERENCES "worktracker_project" ("id") DEFERRABLE INITIALLY DEFERRED, "start_state_id" char(32) NULL REFERENCES "worktracker_state" ("id") DEFERRABLE INITIALLY DEFERRED, "workflow_revision" integer unsigned NOT NULL CHECK ("workflow_revision" >= 0), "is_pathfind" bool NOT NULL);
CREATE TABLE "worktracker_issuetypetransition" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "agent_allowed" bool NOT NULL, "from_state_id" char(32) NOT NULL REFERENCES "worktracker_state" ("id") DEFERRABLE INITIALLY DEFERRED, "issue_type_id" char(32) NOT NULL REFERENCES "worktracker_issuetype" ("id") DEFERRABLE INITIALLY DEFERRED, "to_state_id" char(32) NOT NULL REFERENCES "worktracker_state" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_issue_type_transition" UNIQUE ("issue_type_id", "from_state_id", "to_state_id"));
CREATE TABLE "worktracker_launchbinding" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "prompt" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "issue_type_id" char(32) NOT NULL REFERENCES "worktracker_issuetype" ("id") DEFERRABLE INITIALLY DEFERRED, "state_id" char(32) NOT NULL REFERENCES "worktracker_state" ("id") DEFERRABLE INITIALLY DEFERRED, "auto_start" bool NOT NULL, "subtree_run_enabled" bool NOT NULL, "required_skills" text NOT NULL CHECK ((JSON_VALID("required_skills") OR "required_skills" IS NULL)), "model_id" char(32) NULL REFERENCES "worktracker_agentmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "reasoning_id" char(32) NULL REFERENCES "worktracker_reasoninglevel" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "unique_launch_binding_type_state" UNIQUE ("issue_type_id", "state_id"));
CREATE TABLE "worktracker_project" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "slug" varchar(64) NOT NULL, "description" text NOT NULL, "seq_counter" integer unsigned NOT NULL CHECK ("seq_counter" >= 0), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "workspace_id" char(32) NOT NULL REFERENCES "worktracker_workspace" ("id") DEFERRABLE INITIALLY DEFERRED, "state_revision" bigint unsigned NOT NULL CHECK ("state_revision" >= 0), "manual_module_order" bool NOT NULL);
CREATE TABLE "worktracker_provider" ("id" char(32) NOT NULL PRIMARY KEY, "slug" varchar(64) NOT NULL UNIQUE, "activated" bool NOT NULL, "supports_unattended" bool NOT NULL);
CREATE TABLE "worktracker_reasoninglevel" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar(32) NOT NULL UNIQUE);
CREATE TABLE "worktracker_state" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "group" varchar(20) NOT NULL, "color" varchar(32) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "project_id" char(32) NOT NULL REFERENCES "worktracker_project" ("id") DEFERRABLE INITIALLY DEFERRED, "sort_order" integer unsigned NOT NULL CHECK ("sort_order" >= 0), "is_protected" bool NOT NULL);
CREATE TABLE "worktracker_workspace" ("id" char(32) NOT NULL PRIMARY KEY, "slug" varchar(255) NOT NULL UNIQUE, "name" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "onboarding_required" bool NOT NULL);
CREATE TABLE worktrees (
                    id VARCHAR NOT NULL,
                    task_id VARCHAR NOT NULL UNIQUE,
                    workspace_slug VARCHAR,
                    project_id VARCHAR,
                    module_id VARCHAR,
                    ticket_seq INTEGER,
                    repo_root VARCHAR NOT NULL,
                    path VARCHAR NOT NULL,
                    branch VARCHAR NOT NULL,
                    base_branch VARCHAR NOT NULL,
                    base_commit VARCHAR NOT NULL,
                    status VARCHAR NOT NULL,
                    ephemeral BOOL NOT NULL DEFAULT FALSE,
                    created_at VARCHAR NOT NULL,
                    updated_at VARCHAR NOT NULL,
                    PRIMARY KEY (id)
                );
CREATE INDEX "agent_runs_issue_id_f02b0ea6" ON "agent_runs" ("issue_id");
CREATE INDEX "agent_terminal_sessions_runtime_namespace_a928a9d9"
    ON "agent_terminal_sessions" ("runtime_namespace");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "automation_attempts_issue_id_7cd2982c" ON "automation_attempts" ("issue_id");
CREATE INDEX "automation_attempts_root_attempt_id_5cd48d19" ON "automation_attempts" ("root_attempt_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "graph_runs_module_id_f6c1abdc" ON "graph_runs" ("module_id");
CREATE INDEX "graph_runs_project_id_c350ebc9" ON "graph_runs" ("project_id");
CREATE INDEX "idx_agent_runs_issue_started" ON "agent_runs" ("issue_id", "started_at" DESC);
CREATE INDEX "idx_agent_terminal_sessions_task_created"
    ON "agent_terminal_sessions" ("task_id", "terminated_at", "created_at" DESC);
CREATE INDEX "idx_auto_attempt_issue_created" ON "automation_attempts" ("issue_id", "created_at" DESC);
CREATE INDEX "idx_design_documents_task" ON "design_documents" ("task_id");
CREATE INDEX "launched_tasks_root_id_6a1cc208" ON "launched_tasks" ("root_id");
CREATE UNIQUE INDEX "uniq_auto_attempt_transition_root" ON "automation_attempts" ("transition_id") WHERE "retry_of_id" IS NULL;
CREATE INDEX "worktracker_agentmodel_provider_id_42583db8" ON "worktracker_agentmodel" ("provider_id");
CREATE INDEX "worktracker_agentmodelreasoninglevel_agent_model_id_a01687a1" ON "worktracker_agentmodelreasoninglevel" ("agent_model_id");
CREATE INDEX "worktracker_agentmodelreasoninglevel_reasoning_level_id_7625d8d8" ON "worktracker_agentmodelreasoninglevel" ("reasoning_level_id");
CREATE INDEX "worktracker_attachment_issue_id_b88d0a0b" ON "worktracker_attachment" ("issue_id");
CREATE INDEX "worktracker_issue_blocked_by_from_issue_id_17187412" ON "worktracker_issue_blocked_by" ("from_issue_id");
CREATE UNIQUE INDEX "worktracker_issue_blocked_by_from_issue_id_to_issue_id_5357eff5_uniq" ON "worktracker_issue_blocked_by" ("from_issue_id", "to_issue_id");
CREATE INDEX "worktracker_issue_blocked_by_to_issue_id_1ed13656" ON "worktracker_issue_blocked_by" ("to_issue_id");
CREATE INDEX "worktracker_issue_issue_type_id_9cbb06e1" ON "worktracker_issue" ("issue_type_id");
CREATE INDEX "worktracker_issue_module_id_f92e1b3d" ON "worktracker_issue" ("module_id");
CREATE INDEX "worktracker_issue_parent_id_0f4b390c" ON "worktracker_issue" ("parent_id");
CREATE INDEX "worktracker_issue_project_id_218bdd4b" ON "worktracker_issue" ("project_id");
CREATE UNIQUE INDEX "worktracker_issue_project_id_sequence_id_55f38730_uniq" ON "worktracker_issue" ("project_id", "sequence_id");
CREATE INDEX "worktracker_issue_rank_0fa0887c" ON "worktracker_issue" ("rank");
CREATE INDEX "worktracker_issue_state_id_4f4f824c" ON "worktracker_issue" ("state_id");
CREATE INDEX "worktracker_issuetype_project_id_e5537dfc" ON "worktracker_issuetype" ("project_id");
CREATE UNIQUE INDEX "worktracker_issuetype_project_id_name_1bc218db_uniq" ON "worktracker_issuetype" ("project_id", "name");
CREATE INDEX "worktracker_issuetype_start_state_id_c63c26b4" ON "worktracker_issuetype" ("start_state_id");
CREATE INDEX "worktracker_issuetypetransition_from_state_id_962deb13" ON "worktracker_issuetypetransition" ("from_state_id");
CREATE INDEX "worktracker_issuetypetransition_issue_type_id_0ba764de" ON "worktracker_issuetypetransition" ("issue_type_id");
CREATE INDEX "worktracker_issuetypetransition_to_state_id_16186a4a" ON "worktracker_issuetypetransition" ("to_state_id");
CREATE INDEX "worktracker_launchbinding_issue_type_id_e1186a5f" ON "worktracker_launchbinding" ("issue_type_id");
CREATE INDEX "worktracker_launchbinding_model_id_d0e03899" ON "worktracker_launchbinding" ("model_id");
CREATE INDEX "worktracker_launchbinding_reasoning_id_be752c83" ON "worktracker_launchbinding" ("reasoning_id");
CREATE INDEX "worktracker_launchbinding_state_id_51032313" ON "worktracker_launchbinding" ("state_id");
CREATE INDEX "worktracker_module__f27859_idx" ON "worktracker_issue" ("module_id");
CREATE INDEX "worktracker_parent__529864_idx" ON "worktracker_issue" ("parent_id");
CREATE INDEX "worktracker_project_540084_idx" ON "worktracker_issue" ("project_id", "type");
CREATE INDEX "worktracker_project_workspace_id_7196ac72" ON "worktracker_project" ("workspace_id");
CREATE UNIQUE INDEX "worktracker_project_workspace_id_slug_80399ba5_uniq" ON "worktracker_project" ("workspace_id", "slug");
CREATE INDEX "worktracker_state_project_id_b70c4f38" ON "worktracker_state" ("project_id");
CREATE INDEX "wt_issue_proj_state_rev_idx" ON "worktracker_issue" ("project_id", "state_revision");
