# Generated by Django 6.0.6 on 2026-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDocument',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('module_id', models.CharField()),
                ('task_id', models.CharField()),
                ('scope', models.CharField()),
                ('root_dir', models.CharField()),
                ('rel_path', models.CharField()),
                ('discovered_by_run_id', models.CharField(null=True)),
                ('created_at', models.CharField()),
                ('updated_at', models.CharField()),
            ],
            options={
                'db_table': 'design_documents',
                'indexes': [models.Index(fields=['task_id'], name='idx_design_documents_task')],
                'constraints': [models.UniqueConstraint(fields=('root_dir', 'rel_path'), name='uq_design_doc_path')],
            },
        ),
        migrations.RunSQL(
            sql="""
                DROP TABLE design_documents;
                CREATE TABLE design_documents (
                    id VARCHAR NOT NULL,
                    module_id VARCHAR NOT NULL,
                    task_id VARCHAR NOT NULL,
                    scope VARCHAR NOT NULL,
                    root_dir VARCHAR NOT NULL,
                    rel_path VARCHAR NOT NULL,
                    discovered_by_run_id VARCHAR,
                    created_at VARCHAR NOT NULL,
                    updated_at VARCHAR NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT uq_design_doc_path UNIQUE (root_dir, rel_path)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
