# Generated by Django 6.0.6 on 2026-06-21 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models

def ensure_historical_issue_types(project, IssueType, alias):
    """Keep this historical migration independent of later seed vocabulary."""
    defaults = {}
    for order, (name, level) in enumerate((("Epic", "module"), ("Task", "task"))):
        issue_type, _ = IssueType.objects.using(alias).get_or_create(
            project=project,
            name=name,
            defaults={
                "id": uuid.uuid4(), "level": level, "sort_order": order,
                "is_default": True,
            },
        )
        defaults[level] = issue_type
    return defaults


def backfill(apps, schema_editor):
    """Seed the two default issue types, map existing issues, order states.

    For every existing project: ensure Epic(module) + Task(task) exist, point
    each issue's new ``issue_type`` FK at its level's default by the binary
    ``type`` it already carries, then stamp ``sort_order`` on its states. The
    seed helpers are shared with provision.py, so the result is identical to a
    fresh install. Idempotent — re-running changes nothing.
    """

    Project = apps.get_model("worktracker", "Project")
    Issue = apps.get_model("worktracker", "Issue")
    IssueType = apps.get_model("worktracker", "IssueType")
    State = apps.get_model("worktracker", "State")

    alias = schema_editor.connection.alias if schema_editor is not None else "default"
    for project in Project.objects.using(alias).all():
        defaults_by_level = ensure_historical_issue_types(project, IssueType, alias)
        for issue in Issue.objects.using(alias).filter(
            project=project, issue_type__isnull=True
        ):
            issue.issue_type = defaults_by_level.get(issue.type)
            issue.save(using=alias, update_fields=["issue_type"])
        historical_order = {
            "Backlog": 0, "Todo": 1, "In Progress": 2, "Done": 3, "Cancelled": 4,
        }
        states = sorted(
            State.objects.using(alias).filter(project=project),
            key=lambda state: (historical_order.get(state.name, 99), state.created_at),
        )
        for index, state in enumerate(states):
            if state.sort_order != index:
                state.sort_order = index
                state.save(using=alias, update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0003_issue_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('module', 'Module'), ('task', 'Task')], max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='worktracker.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='worktracker.issuetype'),
        ),
        # Seed types, backfill the FK, and order states. Reverse drops the FK
        # with the AddField above; the data step itself is a no-op on reverse.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
