# Generated by Django 6.0.6 on 2026-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0004_issue_types_and_state_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='worktracker.issue'),
        ),
    ]
