# Generated by Django 6.0.6 on 2026-07-09 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracker', '0010_workflow_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForceTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(blank=True, max_length=64, null=True)),
                ('to_state', models.CharField(blank=True, max_length=64, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='force_transitions', to='worktracker.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
