# Generated by Django 6.0.6 on 2026-07-14 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worktracker", "0014_workspace_onboarding_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="priority",
        ),
    ]
