# Generated by Django 6.0.6 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("worktracker", "0015_remove_issue_priority")]

    operations = [
        migrations.CreateModel(
            name="WorkflowConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("draft", models.JSONField(default=dict)),
                ("active", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issue_type", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="workflow_configuration", to="worktracker.issuetype")),
            ],
        )
    ]
