fragment LocalSettingsFields on LocalSettings {
  recent_profile_index
  profiles {
    name
    workspace_slug
    agent_prompt
    agent_prompts
    module_links {
      module_id
      path
    }
    recent_project_id
    recent_module_ids
  }
  features {
    sidebar
    projects
  }
}

query LoadLocalSettings {
  local_settings {
    ...LocalSettingsFields
  }
}

mutation AddLocalProfile($profile: LocalProfileInput!) {
  add_local_profile(profile: $profile) {
    ...LocalSettingsFields
  }
}

mutation ReplaceLocalProfile($index: Int!, $profile: LocalProfileInput!) {
  replace_local_profile(index: $index, profile: $profile) {
    ...LocalSettingsFields
  }
}

mutation DeleteLocalProfile($index: Int!) {
  delete_local_profile(index: $index) {
    ...LocalSettingsFields
  }
}

mutation SelectLocalProfile($index: Int!) {
  select_local_profile(index: $index) {
    ...LocalSettingsFields
  }
}

mutation ReplaceFeatureFlags($features: LocalFeatureFlagsInput!) {
  replace_feature_flags(features: $features) {
    ...LocalSettingsFields
  }
}
